import { DecideResponse } from "./schemas";

/** Build a nicely formatted Markdown document of a full deliberation result. */
export function buildMarkdown(result: DecideResponse): string {
  const { input, advisers, reviewers, scores, synthesis } = result;
  const lines: string[] = [];

  lines.push("# Crossroads deliberation");
  lines.push("");
  lines.push(`**Decision:** ${input.question}`);
  lines.push(`**Date:** ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push("## Options considered");
  lines.push("");
  input.options.forEach((o, i) => lines.push(`${i + 1}. ${o}`));
  if (input.context) {
    lines.push("");
    lines.push(`**Context:** ${input.context}`);
  }
  lines.push("");

  lines.push("## Recommendation");
  lines.push("");
  lines.push(`**${synthesis.recommendation}**`);
  lines.push("");
  lines.push(`**Confidence:** ${synthesis.confidence}`);
  lines.push("");
  lines.push(`**Why:** ${synthesis.why}`);
  lines.push("");
  lines.push(`**Biggest tradeoff:** ${synthesis.biggestTradeoff}`);
  lines.push("");
  lines.push(`**Biggest risk:** ${synthesis.biggestRisk}`);
  lines.push("");
  lines.push(`**What could change it:** ${synthesis.whatCouldChangeIt}`);
  lines.push("");

  lines.push("## Final scores");
  lines.push("");
  lines.push("_Average of adviser scores, adjusted by anonymous peer-review quality ratings._");
  lines.push("");
  const sorted = [...scores].sort((a, b) => b.adjustedScore - a.adjustedScore);
  sorted.forEach((s, i) => {
    lines.push(
      `${i + 1}. **${s.option}** — ${s.adjustedScore.toFixed(1)}/100 (raw average ${s.averageScore.toFixed(1)})`
    );
    Object.entries(s.perAdviser).forEach(([label, score]) => {
      lines.push(`   - ${label}: ${score}`);
    });
  });
  lines.push("");

  lines.push("## Adviser perspectives");
  lines.push("");
  advisers.forEach((a) => {
    lines.push(`### ${a.label}`);
    lines.push("");
    if (a.status !== "ok" || !a.output) {
      lines.push("_This adviser didn't respond in time and was excluded from scoring._");
      lines.push("");
      return;
    }
    lines.push(a.output.summary);
    lines.push("");
    a.output.scores.forEach((s) => {
      lines.push(`- **${s.option}** — ${s.score}/100: ${s.reasoning}`);
    });
    if (a.output.keyConsiderations.length > 0) {
      lines.push("");
      lines.push("**Key considerations:**");
      a.output.keyConsiderations.forEach((k) => lines.push(`- ${k}`));
    }
    lines.push("");
  });

  lines.push("## Anonymous peer review");
  lines.push("");
  lines.push("_Two reviewers graded every argument for quality and bias without knowing which adviser wrote which._");
  lines.push("");
  reviewers.forEach((r) => {
    const label =
      r.focus === "argument_quality"
        ? "Argument Quality Reviewer"
        : r.focus === "blind_spots"
          ? "Blind Spot Reviewer"
          : r.focus;
    lines.push(`### ${label} (anonymous)`);
    lines.push("");
    if (r.status !== "ok" || !r.output) {
      lines.push("_This reviewer didn't respond in time._");
      lines.push("");
      return;
    }
    if (r.output.blindSpots.length > 0) {
      lines.push("**Blind spots:**");
      r.output.blindSpots.forEach((b) => lines.push(`- ${b}`));
      lines.push("");
    }
    if (r.output.argumentQualityNotes.length > 0) {
      lines.push("**Notes on adviser arguments:**");
      r.output.argumentQualityNotes.forEach((n) => {
        const adj = n.qualityAdjustment > 0 ? `+${n.qualityAdjustment}` : `${n.qualityAdjustment}`;
        lines.push(`- **${n.targetPerspective}** (${adj}): ${n.note}`);
      });
      lines.push("");
    }
  });

  lines.push("---");
  lines.push("_Generated by Crossroads, running locally. Recommendations are AI-generated and not professional advice._");

  return lines.join("\n");
}

/** Copy text to clipboard, with a fallback for older browsers. */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    // Fallback: hidden textarea + execCommand
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

/** Trigger a download of the markdown export as a .md file. */
export function downloadMarkdown(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Slug-ish filename for the export, e.g. crossroads-decision-20261006-1933.md */
export function exportFilename(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `crossroads-decision-${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.md`;
}
